from typing import TypedDict, Optional, List, Any, Dict

class AgentState(TypedDict):
    """
    Represents the state of the multi-agent CBT workflow.
    
    Attributes:
        user_query (str): The initial input/problem description from the user.
        route (Optional[str]): Routing decision - "conversation", "planner", or "draftsman".
        router_response (Optional[str]): Direct response if route is "conversation".
        plan (Optional[str]): The CBT exercise plan generated by the Planner (JSON string).
        planner_scratchpad (Optional[str]): Planner's reasoning trace for draftsman context.
        draft (Optional[str]): The current Markdown CBT exercise draft.
        planner_trace (Optional[List]): Trace of planner's reasoning steps for frontend visibility.
        
        # New fields for critique-revision reflection loop
        current_draft (Optional[str]): Current working draft (updated during revision loop).
        critique_document (Optional[str]): Latest critique from the 3-agent critic.
        critique_data (Optional[Dict]): Structured critique data for processing.
        critique_approved (Optional[bool]): True when critique node approves the draft.
        draft_versions (Optional[List[Dict]]): Version history with content and metadata.
        reflection_iteration (Optional[int]): Current iteration count in the reflection loop.
        max_iterations (Optional[int]): Maximum allowed reflection iterations (default 3).
        protocol_contract (Optional[Dict]): Protocol constraints from draftsman for critic.
        final_presentation (Optional[str]): Final synthesized document after approval.
        revision_notes (Optional[str]): Notes about what was changed in the last revision.
    """
    user_query: str
    route: Optional[str]
    router_response: Optional[str]
    plan: Optional[str]
    planner_scratchpad: Optional[str]
    draft: Optional[str]
    planner_trace: Optional[List[Any]]
    
    # Critique-Revision Loop Fields
    current_draft: Optional[str]
    critique_document: Optional[str]
    critique_data: Optional[Dict[str, Any]]
    critique_approved: Optional[bool]
    draft_versions: Optional[List[Dict[str, Any]]]
    reflection_iteration: Optional[int]
    max_iterations: Optional[int]
    protocol_contract: Optional[Dict[str, Any]]
    final_presentation: Optional[str]
    revision_notes: Optional[str]
    
    # Human-in-the-Loop Fields
    hitl_pending: Optional[bool]           # True when awaiting user approval
    hitl_decision: Optional[str]           # "approved", "revised", "rejected"
    hitl_feedback: Optional[str]           # User's revision feedback (for planner)
    plan_revision_count: Optional[int]     # How many times user requested revision

